# Generated by Django 5.2 on 2026-01-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_offer_rename_payment_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gift_wrap',
            field=models.BooleanField(default=False),
        ),
    ]
